enginetoday/account/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('enginetoday.account.views',
    url(r'^$', 'settings', name='settings'),
    url(r'^profile/$', 'profile', name='profile'),
    url(r'^emails/$', 'emails', name='emails'),
    url(r'^picture/$', 'picture', name='picture'),
    url(r'^password/$', 'password', name='password'),
    url(r'^upload_picture/$', 'upload_picture', name='upload_picture'),
    url(r'^save_uploaded_picture/$', 'save_uploaded_picture', name='save_uploaded_picture'),
)

enginetoday/authentication/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('enginetoday.authentication.views',
    url(r'^signup/$', 'signup', name='signup'),
    url(r'^signin/$', 'signin', name='signin'),
    url(r'^signout/$', 'signout', name='signout'),
    url(r'^reset/$', 'reset', name='reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'reset_confirm', name='password_reset_confirm'),
    url(r'^success/$', 'success', name='success'),

    # url(r'^(?P<username>[^/]+)/$', 'reviews.views.reviews', name='reviews'),
)

enginetoday/main/urls.py
# urls.py (the URL configuration)

from django.conf.urls import url, include


from enginetoday.main.views import *


app_name = 'main'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^gallery/$', GalleryView.as_view(), name='gallery'),
    url(r'^error/$', ErrorView.as_view(), name='error'),
    url(r'^account/confirm-email/$', ConfirmemailView.as_view(), name='confirm-email'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^account/create-account/$', CreateaccountView.as_view(), name='create-account'),
    url(r'^account/forgot-password/$', ForgotpasswordView.as_view(), name='forgot-password'),
    url(r'^account/profile/$', ProfileView.as_view(), name='Profile'),


#   url(r'^account/register/$', RegisterView.as_view(), name='register'),
#   url(r'^account/signin/$', SigninView.as_view(), name='signin'),


    url(r'^account/thanks-for-activating-account/$', ThanksforactivatingaccountView.as_view(),
        name='thanks-for-activating-account'),

    url(r'^account/thanks-for-creating-account/$', ThanksforcreatingaccountView.as_view(),
        name='thanks-for-creating-account'),

    url(r'^cars/cars/$', CarsView.as_view(), name='cars'),

    url(r'^cars/cars-detail/$', CarsdDetailView.as_view(), name='cars-detail'),

    url(r'^sell/saved-sell/$', SavedsellView.as_view(), name='saved-sell'),
    url(r'^sell/sell/$', SellView.as_view(), name='sell'),

    url(r'^(?P<pk>\d+)/$', DetailView.as_view(), name='detail'),
    url(r'^edit/create/$', AnnounceCreate.as_view(), name='announce-create'),
    url(r'^edit/update/(?P<pk>\d+)/$', AnnounceUpdate.as_view(), name='announce-update'),
    url(r'^edit/delete/(?P<pk>\d+)/$', AnnounceDelete.as_view(), name='announce-delete'),

    # url(r'^accounts/', include('django.contrib.auth.urls'))
    # url(r'^(?P<announce_id>[0-9]+)$', views.detail, name='cars-detail'),
]

enginetoday/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('enginetoday',
    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('enginetoday.main.urls', namespace='main')),

    url(r'^account/', include('enginetoday.authentication.urls', namespace="account")),
    url(r'^settings/', include('enginetoday.account.urls', namespace='settings')),


    url(r'^form/', include('enginetoday.advertise.urls', namespace='advertise')),
    url(r'^ajaximage/', include('ajaximage.urls')),
    # url(r'^(?P<username>[^/]+)/$', 'advertise.views.advertises', name='advertises'),
)

#  to test the uploads in the development environment
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

enginetoday/main/models.py
# models.py (the database tables)


from django.db import models
from django.core.urlresolvers import reverse


class User(models.Model):
    CREATED = 'created'
    VALIDATED = 'validated'
    DELETED = 'deleted'
    status_choice_s = (
        (CREATED, 'Created'),
        (VALIDATED, 'Validated'),
        (DELETED, 'Deleted'),
    )
    ANNOUNCER = 'announcer'
    NORMAL_ADMIN = 'normal_admin'
    SUPER_ADMIN = 'super_admin'
    role_choice_s = (
        (ANNOUNCER, 'Announcer'),
        (NORMAL_ADMIN, 'Normal Admin'),
        (SUPER_ADMIN, 'Super Admin'),
    )

    status = models.CharField(max_length=140, choices=status_choice_s, default=CREATED)
    password_hash = models.CharField(max_length=140)
    email = models.EmailField(max_length=140, unique=True)
    # display_name = models.CharField(max_length=140, unique=True)
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)
    role = models.CharField(max_length=140, choices=role_choice_s, default=ANNOUNCER)
    address = models.CharField(max_length=140)
    city = models.CharField(max_length=140)
    county = models.CharField(max_length=140)
    phone_number = models.CharField(max_length=140)
    birth = models.CharField(max_length=140)
    reg_date = models.DateTimeField('date registered')

    def get_absolute_url(self):
        return reverse('main:profile', kwargs={'pk': self.pk})  # form inserted into db, then redirect to this url.

    def __str__(self):
        return self.email


class Announce(models.Model):
    # status
    DRAFT_STARTED = 'draft_started'
    DRAFT_FINISHED = 'draft_finished'
    CREATED = 'created'
    PUBLISHED = 'published'
    EXPIRED_AUTO = 'expired_auto'
    EXPIRED_MANUAL = 'expired_manual'
    DELETED = 'deleted'
    REPLACED = 'replaced'
    status_choice_s = (
        (DRAFT_STARTED, 'Draft Started'),
        (DRAFT_FINISHED, 'Draft Finished'),
        (CREATED, 'Created'),
        (PUBLISHED, 'Published'),
        (EXPIRED_AUTO, 'Expired Auto'),
        (EXPIRED_MANUAL, 'Expired Manual'),
        (DELETED, 'deleted'),
        (REPLACED, 'replaced'),
    )
    # type
    SMALL_CAR = 'small_car'
    MEDIUM_CAR = 'medium_car'
    LARGE_CAR = 'large_car'
    EXECUTIVE_CAR = 'executive_car'
    LUXURY_CAR = 'luxury_car'
    SPORTS_COUPES = 'sports_coupes'
    MULTIPURPOSE_CAR = 'multipurpose_car'
    SUV = 'suv'
    FAMILY_BUS = 'family_bus'
    type_choice_s = (
        (SMALL_CAR, 'Small Car'),
        (MEDIUM_CAR, 'Medium Car'),
        (LARGE_CAR, 'Large Car'),
        (EXECUTIVE_CAR, 'Executive Car'),
        (LUXURY_CAR, 'Luxury Car'),
        (SPORTS_COUPES, 'Sports Coupes'),
        (MULTIPURPOSE_CAR, 'Multipurpose Car'),
        (SUV, 'SUV'),
        (FAMILY_BUS, 'Family Bus'),
    )
    # gear box
    AUTOMATIC = 'automatic'
    MANUAL = 'manual'
    gear_box_choice_s = (
        (AUTOMATIC, 'Automatic'),
        (MANUAL, 'Manual'),
    )
    # fuel
    PETROL = 'petrol'
    DIESEL = 'diesel'
    ELECTRONIC = 'electronic'
    HYBRID = 'hybrid'
    fuel_choice_s = (
        (PETROL,  'Petrol'),
        (DIESEL,  'Diesel'),
        (ELECTRONIC,  'Electronic'),
        (HYBRID,  'Hybrid'),
    )
    # verified_media
    VERIFIED_MEDIA_NO = 0
    VERIFIED_MEDIA_YES = 1
    verified_media_choice_s = (
        (VERIFIED_MEDIA_NO, 'Nej'),
        (VERIFIED_MEDIA_YES, 'Ja'),
    )

    owner_id = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=140)
    status = models.CharField(max_length=140, choices=status_choice_s, default=CREATED)
    location = models.CharField(max_length=140, default='DEFAULT VALUE')
    brand = models.CharField(max_length=140)
    model = models.CharField(max_length=140)
    model_year = models.IntegerField()
    mileage = models.IntegerField()
    type = models.CharField(max_length=140, choices=type_choice_s, default=SUV)
    gear_box = models.CharField(max_length=140, choices=gear_box_choice_s, default=AUTOMATIC)
    fuel = models.CharField(max_length=140, choices=fuel_choice_s, default=PETROL)
    description = models.CharField(max_length=2048)
    price = models.IntegerField()
    submit_time = models.DateTimeField('submit time')
    publish_time = models.DateTimeField()
    verified_media = models.IntegerField(choices=verified_media_choice_s, default=VERIFIED_MEDIA_NO)
    last_update_time = models.DateTimeField()
    expire_time = models.DateTimeField()
    filename = models.CharField(max_length=140, default='20160904/1.jpg')


    def get_absolute_url(self):
        return reverse('main:cars-detail', kwargs={'pk': self.pk})  # form inserted into db, then redirect to this url.

    def __str__(self):
        return self.title


class Media(models.Model):
    IMAGE = 'image'
    YOUTUBE = 'youtube'
    AUDIO = 'audio'
    type_choice_s = (
        (IMAGE, 'Image'),
        (YOUTUBE, 'Video'),
        (AUDIO, 'Audio'),
    )

    announce_id = models.ForeignKey(Announce, on_delete=models.CASCADE)
    type = models.CharField(max_length=140, choices=type_choice_s, default=IMAGE)
    filename = models.CharField(max_length=140, default='')

    def __str__(self):
        return self.announce_id

enginetoday/main/views.py
# views.py (the business logic)
from django.http import Http404
# from django.urls.base import reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login

from django.views.generic import View
from django.template import loader

from enginetoday.main.models import *
from enginetoday.main.models import User, Announce, Media


class IndexView(generic.ListView):
    template_name = 'main/index.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class GalleryView(generic.ListView):
    template_name = 'main/gallery.html'
    context_object_name = 'announceList'
    menuActiveGallery = 1

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class ErrorView(generic.ListView):
    template_name = 'main/error.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class ConfirmemailView(generic.ListView):
    template_name = 'main/account/confirm-email.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class ContactView(generic.ListView):
    template_name = 'main/contact.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class CreateaccountView(generic.ListView):
    template_name = 'main/account/create-account.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class ForgotpasswordView(generic.ListView):
    template_name = 'main/account/forgot-password.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class ProfileView(generic.ListView):
    template_name = 'main/account/profile.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class RegisterView(generic.ListView):
    template_name = 'main/account/register.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


# class SigninView(generic.ListView):
#    template_name = 'main/account/signin.html'
 #   context_object_name = 'announceList'

 #   def get_queryset(self):
 #       return Announce.objects.all().order_by("-submit_time")


class ThanksforactivatingaccountView(generic.ListView):
    template_name = 'main/account/thanks-for-activating-account.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class ThanksforcreatingaccountView(generic.ListView):
    template_name = 'main/account/thanks-for-creating-account.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class CarsView(generic.ListView):
    template_name = 'main/cars/cars.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class CarsdDetailView(generic.DetailView):
    model = Announce
    template_name = 'main/cars/cars-detail.html'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class SavedsellView(generic.ListView):
    template_name = 'main/sell/saved-sell.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class SellView(generic.ListView):
    template_name = 'main/sell/sell.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


# class AdvertisePublishView(FormView):
#     template_name = 'main/sell/sell.html'
#     form_class = AdvertisePublishForm
#     success_url = '/saved-sell/'
#
#     def form_valid(self, form):
#         form.save(self.request.user.username)
#         return super(AdvertisePublishView, self).form_valid(form)


class DetailView(generic.DetailView):
    model = Announce
    local_fields = Announce._meta.local_fields
    fields = [one_field.name for one_field in local_fields][2:]
    context_object_name = 'announceDetail'


class AnnounceCreate(CreateView):
    model = Announce
    local_fields = Announce._meta.local_fields
    fields = [one_field.name for one_field in local_fields][2:]


class AnnounceUpdate(UpdateView):
    model = Announce
    local_fields = Announce._meta.local_fields
    fields = [one_field.name for one_field in local_fields][2:]


class AnnounceDelete(DeleteView):
    model = Announce
    local_fields = Announce._meta.local_fields
    fields = [one_field.name for one_field in local_fields][2:]
    # success_url = reverse_lazy('main:index')


class UserIndexView(generic.ListView):
    template_name = 'main/gallery.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return User.objects.all()


class UserDetailView(generic.DetailView):
    model = User
    local_fields = User._meta.local_fields
    fields = [one_field.name for one_field in local_fields][2:]
    context_object_name = 'announceDetail'


class UserCreate(CreateView):
    model = User
    local_fields = User._meta.local_fields
    fields = [one_field.name for one_field in local_fields][2:]


class UserUpdate(UpdateView):
    model = User
    local_fields = User._meta.local_fields
    fields = [one_field.name for one_field in local_fields][2:]


class UserceDelete(DeleteView):
    model = User
    # success_url = reverse_lazy('main:index')


# class UserFormView(View):
#     form_class = UserForm
#     template_name = 'main/account/register.html'
#
#     # display blank form
#     def get(self, request):
#         form = self.form_class(None)
#         return render(request, self.template_name, {'form': form})
#
#     # process form data
#     def post(self, request):
#         form = self.form_class(request.Post)
#
#         if form.is_valid():
#
#             user = form.save(commit=false)
#
#             # cleaned (normalized) data
#             username = form.cleaned_data['username']
#             password = form.cleaned_data['password']
#             user.set_password(password)
#             user.save()
#
#             # returns User objects if credentials are correct
#             user = authenticate(username=username, password=password)
#
#             if user is not None:
#
#                 if user.is_active:
#                     login(request, user)
#                     return redirect('music:index')
#
#         return render(request, self.template_name, {'form': form})


# def index(request):
#     all_announce = Announce.objects.all()
#     template = loader.get_template('main/cars/cars')
#     context = {
#         'all_announce': all_announce,
#     }
#     return render(request, 'main/cars/cars', {'all_announce': all_announce})
#
#
# def detail(request, announce_id):
#     try:
#         announce = Announce.objects.get(pk=announce_id)
#     except Announce.DoesNotExist:
#         raise Http404("Car does not exist")
#     return render(request, 'main/cars/cars-detail', {'announce': announce})

enginetoday/main/templates/main/announce_confirm_delete.html
<form action="" method="post">
{% csrf_token %}
<input type="hidden"
       name="after"
       value="{{ object.item.get_absolute_url }}" />
<input type="submit"
       value="Confirm to Delete"
       name="DeleteAndShowItem" />
</form>

enginetoday/main/templates/main/announce_detail.html
{% extends "main/content-frame.html" %}

{% block content %}
    <h3>{{announceDetail.title}}</h3>
    <h6>{{announceDetail.submit_time}}</h6>
    {{announceDetail.description|safe|linebreaks}} <!-- the "safe" filter tells jinja that the string is safe (no need to escape html tags), so we can have html tags taking effect (come into operation) instead of escaped and displayed as plain text -->
{% endblock %}

enginetoday/main/templates/main/announce_form.html
{% extends "main/base.html" %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">

                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include "main/form-group.html"%}
                            <div class="form-group">
                                <div class="col-sm-10 col-sm-offset-2">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

enginetoday/main/templates/main/announce_list.html
{% extends "main/content-frame.html" %}

{% block content %}
    {% for announceDetail in announceList %}
    <h5>{{ announceDetail.submit_time|date:"Y-m-d" }} <a href="/announce/{{announceDetail.id}}">{{announceDetail.title}}</a></h5> <!-- jinja: apply a filter to format date -->
    {% endfor %}
{% endblock %}

enginetoday/main/templates/main/base_home.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>

	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock %}</title>

     <!-- Favicon -->
    <!--<link rel="shortcut icon" href="../static/main/img/favicon.ico" type="image/x-icon">-->
    <link rel="shortcut icon" href="{% static 'main/img/favicon.ico' %}" type="image/x-icon">

    <!-- Font awesome -->
    <link href="{% static 'main/css/font-awesome.css' %}" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="{% static 'main/css/bootstrap.css' %}" rel="stylesheet">
    <!-- slick slider -->
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/slick.css' %}/">
    <!-- price picker slider -->
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/nouislider.css' %}/">
    <!-- Fancybox slider -->
    <link rel="stylesheet" href="{% static 'main/css/jquery.fancybox.css' %}" type="text/css" media="screen" />
    <!-- Theme color -->
    <link id="switcher" href="{% static 'main/css/theme-color/default-theme.css' %}" rel="stylesheet">

    <!-- Main style sheet -->
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">

    <!-- Google Font -->
    <link href='https://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

<body class="aa-price-range">
  <!-- Pre Loader -->
  <div id="aa-preloader-area">
    <div class="pulse"></div>
  </div>
  <!-- SCROLL TOP BUTTON -->
    <a class="scrollToTop" href="#"><i class="fa fa-angle-double-up"></i></a>
  <!-- END SCROLL TOP BUTTON -->




  <!-- Start header section -->
  <header id="aa-header">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-header-area">
            <div class="row">
              <div class="col-md-6 col-sm-6 col-xs-6">
                <div class="aa-header-left">
                  <div class="aa-telephone-no">
                    <span class="fa fa-phone"></span>
                    +46 1234567
                  </div>
                  <div class="aa-email hidden-xs">
                    <span class="fa fa-envelope-o"></span> info@enginetoday.com
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-sm-6 col-xs-6">
                <div class="aa-header-right">
                    {% if user.is_authenticated %}
{#                         <ul class="nav navbar-nav navbar-right">#}
{#            <li>#}
{#              <a href="{% url 'reviews' user.username %}">#}
{#                <span data-toggle="tooltip" data-placement="bottom" data-container="body" title="My profile">{{ user.profile.get_screen_name }}</span>#}
{#              </a>#}
{#            </li>#}
{#            <li>#}
{#              <span class="navbar-text username-divider"></span>#}
{#            </li>#}
{#            {% comment %}#}
{#            <li>#}
{#              <a href="{% url 'library:index' %}">#}
{#                Library#}
{#              </a>#}
{#            </li>#}
{#            {% endcomment %}#}
{#            <li>#}
{#              <a href="{% url 'settings:settings' %}">#}
{#                <span data-toggle="tooltip" data-placement="bottom" data-container="body" title="Account settings">#}
{#                  <span class="glyphicon glyphicon-cog"></span>#}
{#                </span>#}
{#              </a>#}
{#            </li>#}
{#            <li>#}
{#              <a href="{% url 'account:signout' %}">#}
{#                <span data-toggle="tooltip" data-placement="bottom" data-container="body" title="Sign out">#}
{#                  <span class="glyphicon glyphicon-log-out"></span>#}
{#                </span>#}
{#              </a>#}
{#            </li>#}
{#          </ul>#}
                        <a href="{% url 'settings:settings' %}" class="aa-register">
                  Settings  <span class="glyphicon glyphicon-cog"></span>
                  </a>
                  <a href="{% url 'account:signout' %}" class="aa-login">
                 Logout  <span class="glyphicon glyphicon-log-out"></span>
                  </a>
                    {% else %}
                  <a href="{% url 'account:signup' %}" class="aa-register">
                  Register  <span class="glyphicon glyphicon-registration-mark"></span>
                  </a>
                  <a href="{% url 'account:signin' %}" class="aa-login">
                 Login  <span class="glyphicon glyphicon-log-in"></span>
                  </a>
                      {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- End header section -->

  <!-- Start menu section -->
  <section id="aa-menu-area">
    <nav class="navbar navbar-default main-navbar" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <!-- FOR MOBILE VIEW COLLAPSED BUTTON -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- LOGO -->
          <!-- Text based logo -->
           <a class="navbar-brand aa-logo" href="{% url 'main:index' %}"> <span> EngineToday</span></a>
           <!-- Image based logo -->
           <!-- <a class="navbar-brand aa-logo-img" href="index.html"><img src="../static/main/img/logo.png" alt="logo"></a> -->
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul id="top-menu" class="nav navbar-nav navbar-right aa-main-nav">
            <li class="{% block menuActiveHome %}{% endblock %}"><a href="{% url 'main:index' %}">HEM</a></li>
             <li class="{% block menuActiveCar %}{% endblock %}" class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'main:cars' %}">CARS <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'main:cars' %}">CARS</a></li>
                <li><a href="{% url 'main:cars-detail' %}">CARS DETAIL</a></li>
              </ul>
            </li>
            <li><a href="{% url 'main:gallery' %}">GALLERY</a></li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'main:sell' %}">ADVERTISE<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'main:sell' %}">ADVERTISE</a></li>
                <li><a href="{% url 'main:saved-sell' %}">MY ADVERTISEMENT</a></li>
              </ul>
            </li>
            <li><a href="{% url 'main:contact' %}">CONTACT</a></li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
  </section>
  <!-- End menu section -->


  {% block content %}{% endblock %}


  <!-- Footer -->
  <footer id="aa-footer">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
        <div class="aa-footer-area">
          <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="aa-footer-middle">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-google-plus"></i></a>
                <a href="#"><i class="fa fa-youtube"></i></a>
              </div>
            </div>
            <div class="col-md-7 col-sm-12 col-xs-12">
              <div class="aa-footer-right">
                <a href="#">Hem</a>
                <a href="#">Support</a>
                <a href="#">License</a>
                <a href="#">FAQ</a>
                <a href="#">Privacy & Term</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    </div>
  </footer>
  <!-- / Footer -->

  <!-- jQuery library -->
  <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> -->
  <script src="{% static 'main/js/jquery.min.js' %}"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="{% static 'main/js/bootstrap.js' %}"></script>
  <!-- slick slider -->
  <script type="text/javascript" src="{% static 'main/js/slick.js' %}"></script>
  <!-- Price picker slider -->
  <script type="text/javascript" src="{% static 'main/js/nouislider.js' %}"></script>
   <!-- mixit slider -->
  <script type="text/javascript" src="{% static 'main/js/jquery.mixitup.js' %}"></script>
  <!-- Add fancyBox -->
  <script type="text/javascript" src="{% static 'main/js/jquery.fancybox.pack.js' %}"></script>
  <!-- Custom js -->
  <script src="{% static 'main/js/custom.js' %}"></script>

  </body>
</html>