enginetoday/account/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('enginetoday.account.views',
    url(r'^$', 'settings', name='settings'),
    url(r'^profile/$', 'profile', name='profile'),
    url(r'^emails/$', 'emails', name='emails'),
    url(r'^picture/$', 'picture', name='picture'),
    url(r'^password/$', 'password', name='password'),
    url(r'^upload_picture/$', 'upload_picture', name='upload_picture'),
    url(r'^save_uploaded_picture/$', 'save_uploaded_picture', name='save_uploaded_picture'),
)

enginetoday/authentication/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('enginetoday.authentication.views',
    url(r'^signup/$', 'signup', name='signup'),
    url(r'^signin/$', 'signin', name='signin'),
    url(r'^signout/$', 'signout', name='signout'),
    url(r'^reset/$', 'reset', name='reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'reset_confirm', name='password_reset_confirm'),
    url(r'^success/$', 'success', name='success'),

    # url(r'^(?P<username>[^/]+)/$', 'reviews.views.reviews', name='reviews'),
)

enginetoday/main/urls.py
# urls.py (the URL configuration)

from django.conf.urls import url, include


from enginetoday.main.views import *


app_name = 'main'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^gallery/$', GalleryView.as_view(), name='gallery'),
    url(r'^error/$', ErrorView.as_view(), name='error'),
    url(r'^account/confirm-email/$', ConfirmemailView.as_view(), name='confirm-email'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^account/create-account/$', CreateaccountView.as_view(), name='create-account'),
    url(r'^account/forgot-password/$', ForgotpasswordView.as_view(), name='forgot-password'),
    url(r'^account/profile/$', ProfileView.as_view(), name='Profile'),


#   url(r'^account/register/$', RegisterView.as_view(), name='register'),
#   url(r'^account/signin/$', SigninView.as_view(), name='signin'),


    url(r'^account/thanks-for-activating-account/$', ThanksforactivatingaccountView.as_view(),
        name='thanks-for-activating-account'),

    url(r'^account/thanks-for-creating-account/$', ThanksforcreatingaccountView.as_view(),
        name='thanks-for-creating-account'),

    url(r'^cars/cars/$', CarsView.as_view(), name='cars'),

    url(r'^cars/cars-detail/$', CarsdDetailView.as_view(), name='cars-detail'),

    url(r'^sell/saved-sell/$', SavedsellView.as_view(), name='saved-sell'),
    url(r'^sell/sell/$', SellView.as_view(), name='sell'),

    url(r'^(?P<pk>\d+)/$', DetailView.as_view(), name='detail'),
    url(r'^edit/create/$', AnnounceCreate.as_view(), name='announce-create'),
    url(r'^edit/update/(?P<pk>\d+)/$', AnnounceUpdate.as_view(), name='announce-update'),
    url(r'^edit/delete/(?P<pk>\d+)/$', AnnounceDelete.as_view(), name='announce-delete'),

    # url(r'^accounts/', include('django.contrib.auth.urls'))
    # url(r'^(?P<announce_id>[0-9]+)$', views.detail, name='cars-detail'),
]

enginetoday/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('enginetoday',
    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('enginetoday.main.urls', namespace='main')),

    url(r'^account/', include('enginetoday.authentication.urls', namespace="account")),
    url(r'^settings/', include('enginetoday.account.urls', namespace='settings')),


    url(r'^form/', include('enginetoday.advertise.urls', namespace='advertise')),
    url(r'^ajaximage/', include('ajaximage.urls')),
    # url(r'^(?P<username>[^/]+)/$', 'advertise.views.advertises', name='advertises'),
)

#  to test the uploads in the development environment
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

enginetoday/account/views.py
# coding: utf-8

import os
from PIL import Image


from django.core.urlresolvers import reverse as r
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseForbidden
from django.contrib import messages
from django.template import RequestContext
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, get_object_or_404, render
from django.conf import settings as django_settings
from django.contrib.auth import update_session_auth_hash

from enginetoday.account.forms import UserEmailForm, ProfileForm, PasswordForm


@login_required
def settings(request):
    return redirect('/settings/profile/')


@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            messages.success(request, u'Your profile were successfully edited.')
            return redirect(r('settings:profile'))
    else:
        form = ProfileForm(instance=request.user.profile)
    return render(request, 'settings/profile.html', { 'form': form })


@login_required
def picture(request):
    uploaded_picture = False
    try:
        if request.GET['upload_picture'] == 'uploaded':
            uploaded_picture = True
    except Exception as e:
        uploaded_picture = False
    return render(request, 'settings/picture.html', { 'uploaded_picture': uploaded_picture })

@login_required
def emails(request):
    if request.method == 'POST':
        form = UserEmailForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, u'Account Email changed successfully.')
        else:
            messages.error(request, u'Please correct the error below.')
    else:
        form = UserEmailForm(instance=request.user)
    return render(request, 'settings/emails.html', { 'form' : form })


@login_required
def password(request):
    if request.method == 'POST':
        form = PasswordForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, u'Password changed successfully.')
            update_session_auth_hash(request, form.user)
        else:

            messages.error(request, u'Please correct the error below.')
    else:
        form = PasswordForm(request.user)
    return render(request, 'settings/password.html', { 'form' : form })


@login_required
def upload_picture(request):
    try:
        f = request.FILES['picture']
        ext = os.path.splitext(f.name)[1].lower()
        valid_extensions = ['.gif', '.png', '.jpg', '.jpeg', '.bmp']
        if ext in valid_extensions:
            filename = django_settings.MEDIA_ROOT + '/profile_pictures/' + request.user.username + '_tmp.jpg'
            with open(filename, 'wb+') as destination:
                for chunk in f.chunks():
                    destination.write(chunk)
            im = Image.open(filename)
            width, height = im.size
            if width > 560:
                new_width = 560
                new_height = (height * 560) / width
                new_size = new_width, new_height
                im.thumbnail(new_size, Image.ANTIALIAS)
                im.save(filename)
            return redirect('/settings/picture/?upload_picture=uploaded')
        else:
            messages.error(request, u'Invalid file format.')
    except Exception as e:
        messages.error(request, u'An expected error occurred.')
    return redirect('/settings/picture/')


@login_required
def save_uploaded_picture(request):
    try:
        x = int(request.POST['x'])
        y = int(request.POST['y'])
        w = int(request.POST['w'])
        h = int(request.POST['h'])
        tmp_filename = django_settings.MEDIA_ROOT + '/profile_pictures/' + request.user.username + '_tmp.jpg'
        filename = django_settings.MEDIA_ROOT + '/profile_pictures/' + request.user.username + '.jpg'
        im = Image.open(tmp_filename)
        cropped_im = im.crop((x, y, w+x, h+y))
        cropped_im.thumbnail((200, 200), Image.ANTIALIAS)
        cropped_im.save(filename)
        os.remove(tmp_filename)
        return HttpResponse(django_settings.MEDIA_URL + 'profile_pictures/' + request.user.username + '.jpg')
    except Exception as e:
        return HttpResponseBadRequest()

enginetoday/main/views.py
# views.py (the business logic)
from django.http import Http404
# from django.urls.base import reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login

from django.views.generic import View
from django.template import loader

from enginetoday.main.models import *
from enginetoday.main.models import User, Announce, Media


class IndexView(generic.ListView):
    template_name = 'main/index.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class GalleryView(generic.ListView):
    template_name = 'main/gallery.html'
    context_object_name = 'announceList'
    menuActiveGallery = 1

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class ErrorView(generic.ListView):
    template_name = 'main/error.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class ConfirmemailView(generic.ListView):
    template_name = 'main/account/confirm-email.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class ContactView(generic.ListView):
    template_name = 'main/contact.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class CreateaccountView(generic.ListView):
    template_name = 'main/account/create-account.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class ForgotpasswordView(generic.ListView):
    template_name = 'main/account/forgot-password.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class ProfileView(generic.ListView):
    template_name = 'main/account/profile.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class RegisterView(generic.ListView):
    template_name = 'main/account/register.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


# class SigninView(generic.ListView):
#    template_name = 'main/account/signin.html'
 #   context_object_name = 'announceList'

 #   def get_queryset(self):
 #       return Announce.objects.all().order_by("-submit_time")


class ThanksforactivatingaccountView(generic.ListView):
    template_name = 'main/account/thanks-for-activating-account.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class ThanksforcreatingaccountView(generic.ListView):
    template_name = 'main/account/thanks-for-creating-account.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class CarsView(generic.ListView):
    template_name = 'main/cars/cars.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class CarsdDetailView(generic.DetailView):
    model = Announce
    template_name = 'main/cars/cars-detail.html'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class SavedsellView(generic.ListView):
    template_name = 'main/sell/saved-sell.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


class SellView(generic.ListView):
    template_name = 'main/sell/sell.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return Announce.objects.all().order_by("-submit_time")


# class AdvertisePublishView(FormView):
#     template_name = 'main/sell/sell.html'
#     form_class = AdvertisePublishForm
#     success_url = '/saved-sell/'
#
#     def form_valid(self, form):
#         form.save(self.request.user.username)
#         return super(AdvertisePublishView, self).form_valid(form)


class DetailView(generic.DetailView):
    model = Announce
    local_fields = Announce._meta.local_fields
    fields = [one_field.name for one_field in local_fields][2:]
    context_object_name = 'announceDetail'


class AnnounceCreate(CreateView):
    model = Announce
    local_fields = Announce._meta.local_fields
    fields = [one_field.name for one_field in local_fields][2:]


class AnnounceUpdate(UpdateView):
    model = Announce
    local_fields = Announce._meta.local_fields
    fields = [one_field.name for one_field in local_fields][2:]


class AnnounceDelete(DeleteView):
    model = Announce
    local_fields = Announce._meta.local_fields
    fields = [one_field.name for one_field in local_fields][2:]
    # success_url = reverse_lazy('main:index')


class UserIndexView(generic.ListView):
    template_name = 'main/gallery.html'
    context_object_name = 'announceList'

    def get_queryset(self):
        return User.objects.all()


class UserDetailView(generic.DetailView):
    model = User
    local_fields = User._meta.local_fields
    fields = [one_field.name for one_field in local_fields][2:]
    context_object_name = 'announceDetail'


class UserCreate(CreateView):
    model = User
    local_fields = User._meta.local_fields
    fields = [one_field.name for one_field in local_fields][2:]


class UserUpdate(UpdateView):
    model = User
    local_fields = User._meta.local_fields
    fields = [one_field.name for one_field in local_fields][2:]


class UserceDelete(DeleteView):
    model = User
    # success_url = reverse_lazy('main:index')


# class UserFormView(View):
#     form_class = UserForm
#     template_name = 'main/account/register.html'
#
#     # display blank form
#     def get(self, request):
#         form = self.form_class(None)
#         return render(request, self.template_name, {'form': form})
#
#     # process form data
#     def post(self, request):
#         form = self.form_class(request.Post)
#
#         if form.is_valid():
#
#             user = form.save(commit=false)
#
#             # cleaned (normalized) data
#             username = form.cleaned_data['username']
#             password = form.cleaned_data['password']
#             user.set_password(password)
#             user.save()
#
#             # returns User objects if credentials are correct
#             user = authenticate(username=username, password=password)
#
#             if user is not None:
#
#                 if user.is_active:
#                     login(request, user)
#                     return redirect('music:index')
#
#         return render(request, self.template_name, {'form': form})


# def index(request):
#     all_announce = Announce.objects.all()
#     template = loader.get_template('main/cars/cars')
#     context = {
#         'all_announce': all_announce,
#     }
#     return render(request, 'main/cars/cars', {'all_announce': all_announce})
#
#
# def detail(request, announce_id):
#     try:
#         announce = Announce.objects.get(pk=announce_id)
#     except Announce.DoesNotExist:
#         raise Http404("Car does not exist")
#     return render(request, 'main/cars/cars-detail', {'announce': announce})

enginetoday/main/templates/main/account/base_account.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>

	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock %}</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'main/img/favicon.ico' %}" type="image/x-icon">

    <!-- Font awesome -->
    <link href="{% static 'main/css/font-awesome.css' %}" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="{% static 'main/css/bootstrap.css' %}" rel="stylesheet">
    <!-- Theme color -->
    <link id="switcher" href="{% static 'main/css/theme-color/default-theme.css' %}" rel="stylesheet">

    <!-- Main style sheet -->
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">

    <!-- Google Font -->
    <link href='https://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

  {% block content %}{% endblock %}

</html>

enginetoday/main/templates/main/account/confirm-email.html
{% extends "main/base_generic.html" %}

{% block title %}Enginetoday | Aktivera Konto{% endblock %}

{% block page %}Aktivera Konto{% endblock %}
{% block page1 %}Aktivera Konto{% endblock %}


{% block content %}

  <section id="aa-gallery">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-gallery-area">
            <div class="aa-title">
              <h2>Aktivera Konto</h2>
              <span></span>
               <p>Tack för att du aktiverat ditt konto!</p>
             </div>
          </div>
        </div>
       </div>
    </div>
  </section>

{% endblock %}

enginetoday/main/templates/main/account/forgot-password.html
{% extends "main/account/base_account.html" %}

{% block title %}Enginetoday | Forgot password{% endblock %}

{% block content %}

  <body>   
  <section id="aa-signin">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-signin-area">
            <div class="aa-signin-form">
              <div class="aa-signin-form-title">
                <a class="aa-property-home" href="index.html">Enginetody</a>
                <h4>Glömt ditt lösenord?</h4>
                <p>Skriv in din e-mailadress så skickar vi dina uppgifter till den angivna adressen.</p>
              </div>
              <form class="contactform">
                <div class="aa-single-field">
                  <label for="email">E-postadress <span class="required">*</span></label>
                  <input type="email" required="required" aria-required="true" value="" name="email">
                </div>
                <div class="aa-single-submit" >
                  <input type="submit" value="Nytt lösenord" name="submit">
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section> 

{% endblock content %}

enginetoday/main/templates/main/account/register.html
{% extends "main/account/base_account.html" %}

{% block title %}Enginetoday | Registrera{% endblock %}

{% block content %}
  <body>   
  <section id="aa-signin">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-signin-area">
            <div class="aa-signin-form">
              <div class="aa-signin-form-title">
                <a class="aa-logo aa-property-home" href="{% url 'main:index' %}"><span> EngineToday</span></a>
                <h4>Skapa ditt konto och bo hos oss</h4>
                <p>För att kunna delta i budgivning på enginetoday.se behöver du registrera ett användarkonto. Detta är helt kostnadsfritt.</p>
              </div>
              <form class="contactform" action="/user/" method='post'>{% csrf_token %}
                <div class="aa-single-field">
                  <label for="email">E-postadress <span class="required">*</span></label>
                  <input type="email" required="required" aria-required="true" value="" name="email">
                </div>
                <div class="aa-single-field">
                  <label for="first_name">First Name <span class="required">*</span></label>
                  <input type="text" required="required" aria-required="true" value="" name="first_name">
                </div>
                <div class="aa-single-field">
                  <label for="last_name">Last Name <span class="required">*</span></label>
                  <input type="text" required="required" aria-required="true" value="" name="last_name">
                </div>
                <div class="aa-single-field">
                  <label for="password">Password <span class="required">*</span></label>
                  <input type="password" required="required" name="password"> 
                </div>
                <div class="aa-single-field">
                  <label for="confirm-password">Confirm Password <span class="required">*</span></label>
                  <input type="password" required="required" name="confirm-password"> 
                </div>
                 <div class="aa-single-field">
                  <label for="region">Län <span class="required">*</span></label>
                  <select  id="region" class="form-control" name="region">
                    <option value="0">&laquo;Välj region&raquo;</option>
                    <option value="1" >Norrbotten</option>
                    <option value="2" >Västerbotten</option>
                    <option value="3" >Jämtland</option>
                    <option value="4" >Västernorrland</option>
                    <option value="5" >Gävleborg</option>
                    <option value="6" >Dalarna</option>
                    <option value="7" >Värmland</option>
                    <option value="8" >Örebro</option>
                    <option value="9" >Västmanland</option>
                    <option value="10" >Uppsala</option>
                    <option value="11" >Stockholm</option>
                    <option value="12" >Södermanland</option>
                    <option value="13" >Skaraborg</option>
                    <option value="14" >Östergötland</option>
                    <option value="15" >Göteborg</option>
                    <option value="16" >Älvsborg</option>
                    <option value="17" >Jönköping</option>
                    <option value="18" >Kalmar</option>
                    <option value="19" >Gotland</option>
                    <option value="20" >Halland</option>
                    <option value="21" >Kronoberg</option>
                    <option value="22" >Blekinge</option>
                    <option value="23" >Skåne</option>
                    <option value="99" >Flera platser</option>
                  </select>
                  </div>
                <div class="aa-single-field">
                  <label for="area">Område <span class="required">*</span></label>
                  <select id="area" class="form-control" name="area">
                    <option value="">&laquo;Välj kommun&raquo;</option>
                  </select>
                </div>
                <div class="aa-single-field">
                  <label for="birth">Födelsedatum <span class="required">*</span></label>
                  <input type="password" required="required" name="birth">
                </div>
                <div class="aa-single-field">
                  <label for="mobile_phone">Mobile Phone <span class="required">*</span></label>
                  <input type="password" required="required" name="mobile_phone">
                </div>
                <div class="aa-single-field">
                  <input  type="checkbox"  required="required" name="accept-terms"> 
                  <label for="accept-terms"> I have read and accept the terms .<span class="required">*</span></label>
                </div>
                <div class="aa-single-field">
                  <input  type="checkbox"  checked="checked" required="required" name="accept-newsletter"> 
                  <label for="accept-newsletter"> Yes, I want to receive newsletters from Usedcarforsale.
                  <span class="required">*</span></label>
                </div>
                <div class="aa-single-submit">
                  <input type="submit" value="Create Account" name="submit">
                  <p>Already had an account? <a href="{% url 'main:signin' %}">SIGNIN NOW!</a></p>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section> 


  </body>
{% endblock %}

enginetoday/main/templates/main/account/signin.html
{% extends "main/account/base_account.html" %}

{% block title %}Enginetoday | Signin{% endblock %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

  <body>
  <section id="aa-signin">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-signin-area">
            <div class="aa-signin-form">
              <div class="aa-signin-form-title">
                <a class="aa-property-home" href="{% url 'main:index' %}">Enginetoday</a>
                <h4>Sign in to your account</h4>
              </div>
              <form class="contactform" method="post" action="">{% csrf_token %}
                <div class="aa-single-field">
                  <label for="email">E-postadress {{ form.username.label_tag }} <span class="required">*</span></label>
                  <input type="email" required="required" aria-required="true" value="" name="email">
                </div>
                <div class="aa-single-field">
                  <label for="password">Password <span class="required">*</span></label>
                  <input type="password" name="password">
                </div>
                <div class="aa-single-field">
                <label>
                  <input type="checkbox"> Kom ihåg mig
                </label>
                </div>
                <div class="aa-single-submit">
                  <input type="submit" value="Logga In" class="aa-browse-btn" name="submit">
                  <p><a href="{% url 'main:forgot-password' %}">Glömt lösenord</a><p>
                  <p>Don't Have A Account Yet? <a href="{% url 'main:register' %}">CREATE NOW!</a></p>

                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  </body>
{% endblock %}

enginetoday/main/templates/main/account/thanks-for-activating-account.html
{% extends "main/base_generic.html" %}

{% block title %}Enginetoday | AKTIVgftt2                                                                                                        RA KONTO{% endblock %}

{% block content %}
  <section id="aa-gallery">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-gallery-area">
            <div class="aa-title">
              <h2>Aktivera Konto</h2>
              <span></span>
               <p>Tack för att du aktiverat ditt konto!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

enginetoday/main/templates/main/account/thanks-for-creating-account.html
{% extends "main/base_generic.html" %}

{% block title %}Enginetoday | Tack för att du skapat konto{% endblock %}

{% block content %}
  <!-- Start Proerty header  -->
  <section id="aa-property-header">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-property-header-inner">
            <h2>Tack för att du skapat konto</h2>
            <ol class="breadcrumb">
            <li><a href="#">Hem</a></li>
            <li>ATack för att du skapat konto</li>
          </ol>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End Proerty header  -->
  <section id="aa-gallery">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-gallery-area">
            <div class="aa-title">
              <h2>Tack för att du skapat konto</h2>
              <span></span>
               <p>Tack för din registrering! Du får nu ett bekräftelsemail till den adress du angav. Klicka på länken i mejlet för att verifiera kontot.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}