enginetoday/account/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('enginetoday.account.views',
    url(r'^$', 'settings', name='settings'),
    url(r'^profile/$', 'profile', name='profile'),
    url(r'^emails/$', 'emails', name='emails'),
    url(r'^picture/$', 'picture', name='picture'),
    url(r'^password/$', 'password', name='password'),
    url(r'^upload_picture/$', 'upload_picture', name='upload_picture'),
    url(r'^save_uploaded_picture/$', 'save_uploaded_picture', name='save_uploaded_picture'),
)

enginetoday/advertise/urls.py
from django.conf.urls import patterns, url

from enginetoday.advertise.views import MyView


urlpatterns = patterns('',
    url('', MyView.as_view(), name='form'),
)

enginetoday/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('enginetoday',
    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('enginetoday.main.urls', namespace='main')),

    url(r'^account/', include('enginetoday.authentication.urls', namespace="account")),
    url(r'^settings/', include('enginetoday.account.urls', namespace='settings')),


    url(r'^form/', include('enginetoday.advertise.urls', namespace='advertise')),
    url(r'^ajaximage/', include('ajaximage.urls')),
    # url(r'^(?P<username>[^/]+)/$', 'advertise.views.advertises', name='advertises'),
)

#  to test the uploads in the development environment
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

enginetoday/advertise/models.py
from django.db import models
from ajaximage.fields import AjaxImageField


class Advertise(models.Model):
    image = AjaxImageField()
    thumbnail = AjaxImageField(upload_to='thumbnails', max_height=200,
                               max_width=200, crop=False)

    def __unicode__(self):
        return unicode(self.thumbnail)

    def __str__(self):
        return str(self.thumbnail)

    @property
    def url(self):
        return self.thumbnail.url

    @property
    def path(self):
        return self.thumbnail.path

enginetoday/main/models.py
# models.py (the database tables)


from django.db import models
from django.core.urlresolvers import reverse


class User(models.Model):
    CREATED = 'created'
    VALIDATED = 'validated'
    DELETED = 'deleted'
    status_choice_s = (
        (CREATED, 'Created'),
        (VALIDATED, 'Validated'),
        (DELETED, 'Deleted'),
    )
    ANNOUNCER = 'announcer'
    NORMAL_ADMIN = 'normal_admin'
    SUPER_ADMIN = 'super_admin'
    role_choice_s = (
        (ANNOUNCER, 'Announcer'),
        (NORMAL_ADMIN, 'Normal Admin'),
        (SUPER_ADMIN, 'Super Admin'),
    )

    status = models.CharField(max_length=140, choices=status_choice_s, default=CREATED)
    password_hash = models.CharField(max_length=140)
    email = models.EmailField(max_length=140, unique=True)
    # display_name = models.CharField(max_length=140, unique=True)
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)
    role = models.CharField(max_length=140, choices=role_choice_s, default=ANNOUNCER)
    address = models.CharField(max_length=140)
    city = models.CharField(max_length=140)
    county = models.CharField(max_length=140)
    phone_number = models.CharField(max_length=140)
    birth = models.CharField(max_length=140)
    reg_date = models.DateTimeField('date registered')

    def get_absolute_url(self):
        return reverse('main:profile', kwargs={'pk': self.pk})  # form inserted into db, then redirect to this url.

    def __str__(self):
        return self.email


class Announce(models.Model):
    # status
    DRAFT_STARTED = 'draft_started'
    DRAFT_FINISHED = 'draft_finished'
    CREATED = 'created'
    PUBLISHED = 'published'
    EXPIRED_AUTO = 'expired_auto'
    EXPIRED_MANUAL = 'expired_manual'
    DELETED = 'deleted'
    REPLACED = 'replaced'
    status_choice_s = (
        (DRAFT_STARTED, 'Draft Started'),
        (DRAFT_FINISHED, 'Draft Finished'),
        (CREATED, 'Created'),
        (PUBLISHED, 'Published'),
        (EXPIRED_AUTO, 'Expired Auto'),
        (EXPIRED_MANUAL, 'Expired Manual'),
        (DELETED, 'deleted'),
        (REPLACED, 'replaced'),
    )
    # type
    SMALL_CAR = 'small_car'
    MEDIUM_CAR = 'medium_car'
    LARGE_CAR = 'large_car'
    EXECUTIVE_CAR = 'executive_car'
    LUXURY_CAR = 'luxury_car'
    SPORTS_COUPES = 'sports_coupes'
    MULTIPURPOSE_CAR = 'multipurpose_car'
    SUV = 'suv'
    FAMILY_BUS = 'family_bus'
    type_choice_s = (
        (SMALL_CAR, 'Small Car'),
        (MEDIUM_CAR, 'Medium Car'),
        (LARGE_CAR, 'Large Car'),
        (EXECUTIVE_CAR, 'Executive Car'),
        (LUXURY_CAR, 'Luxury Car'),
        (SPORTS_COUPES, 'Sports Coupes'),
        (MULTIPURPOSE_CAR, 'Multipurpose Car'),
        (SUV, 'SUV'),
        (FAMILY_BUS, 'Family Bus'),
    )
    # gear box
    AUTOMATIC = 'automatic'
    MANUAL = 'manual'
    gear_box_choice_s = (
        (AUTOMATIC, 'Automatic'),
        (MANUAL, 'Manual'),
    )
    # fuel
    PETROL = 'petrol'
    DIESEL = 'diesel'
    ELECTRONIC = 'electronic'
    HYBRID = 'hybrid'
    fuel_choice_s = (
        (PETROL,  'Petrol'),
        (DIESEL,  'Diesel'),
        (ELECTRONIC,  'Electronic'),
        (HYBRID,  'Hybrid'),
    )
    # verified_media
    VERIFIED_MEDIA_NO = 0
    VERIFIED_MEDIA_YES = 1
    verified_media_choice_s = (
        (VERIFIED_MEDIA_NO, 'Nej'),
        (VERIFIED_MEDIA_YES, 'Ja'),
    )

    owner_id = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=140)
    status = models.CharField(max_length=140, choices=status_choice_s, default=CREATED)
    location = models.CharField(max_length=140, default='DEFAULT VALUE')
    brand = models.CharField(max_length=140)
    model = models.CharField(max_length=140)
    model_year = models.IntegerField()
    mileage = models.IntegerField()
    type = models.CharField(max_length=140, choices=type_choice_s, default=SUV)
    gear_box = models.CharField(max_length=140, choices=gear_box_choice_s, default=AUTOMATIC)
    fuel = models.CharField(max_length=140, choices=fuel_choice_s, default=PETROL)
    description = models.CharField(max_length=2048)
    price = models.IntegerField()
    submit_time = models.DateTimeField('submit time')
    publish_time = models.DateTimeField()
    verified_media = models.IntegerField(choices=verified_media_choice_s, default=VERIFIED_MEDIA_NO)
    last_update_time = models.DateTimeField()
    expire_time = models.DateTimeField()
    filename = models.CharField(max_length=140, default='20160904/1.jpg')


    def get_absolute_url(self):
        return reverse('main:cars-detail', kwargs={'pk': self.pk})  # form inserted into db, then redirect to this url.

    def __str__(self):
        return self.title


class Media(models.Model):
    IMAGE = 'image'
    YOUTUBE = 'youtube'
    AUDIO = 'audio'
    type_choice_s = (
        (IMAGE, 'Image'),
        (YOUTUBE, 'Video'),
        (AUDIO, 'Audio'),
    )

    announce_id = models.ForeignKey(Announce, on_delete=models.CASCADE)
    type = models.CharField(max_length=140, choices=type_choice_s, default=IMAGE)
    filename = models.CharField(max_length=140, default='')

    def __str__(self):
        return self.announce_id

enginetoday/advertise/forms.py
from django import forms

from ajaximage.widgets import AjaxImageWidget


class AjaxImageUploadForm(forms.Form):
    images = forms.FileField(widget=AjaxImageWidget())

enginetoday/advertise/views.py
from django.shortcuts import render
from django.views.generic import FormView

from enginetoday.advertise.forms import AjaxImageUploadForm


class MyView(FormView):
    template_name = 'advertise/form.html'
    form_class = AjaxImageUploadForm

enginetoday/advertise/templates/reviews/new.html
{% extends 'base.html' %}

{% block javascript %}
  <script>
    $(function () {
      $("#id_title").focus();
    });
  </script>
{% endblock %}

{% block content %}
  <h2 class="page-header">Create a new review</h2>
  <form method="post">
    {% csrf_token %}
    {% include 'form_vertical.html' with form=form %}
    <div class="form-group">
      <button type="submit" class="btn btn-success">Create review</button>
      <a href="{% url 'reviews' user.username %}" class="btn btn-default">Cancel</a>
    </div>
  </form>
{% endblock content %}

enginetoday/advertise/templates/reviews/review.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}{{ review.title }}{% endblock %}

{% block javascript %}
  <script>
  var contacts = [
    {% for contact in user.profile.get_following %}
      { 
        pk: '{{ contact.pk }}', 
        email: '{{ contact.email }}', 
        name: '{{ contact.profile.get_screen_name }}' 
      }{% if not forloop.last %}, {% endif %}
    {% endfor %}
  ];
  </script>
  <script src="{% static 'js/review.js' %}?_=1"></script>
{% endblock %}

{% block content %}

  {% include "reviews/review_header.html" with active_menu="review" %}

  <div class="row">
    <div class="col-sm-7 col-md-8 col-lg-9">
      <form method="post">
        {% csrf_token %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Review details</h3>
          </div>
          <div class="panel-body">
            {% include 'form_vertical.html' with form=form %}
          </div>
          <div class="panel-footer">
            <button type="submit" class="btn btn-success">
              <span class="glyphicon glyphicon-ok"></span>
              Save
            </button>
          </div>
        </div>
      </form>
    </div>
    <div class="col-sm-5 col-md-4 col-lg-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Authors</h3>
        </div>
        <ul class="list-group authors" data-remove-url="{% url 'reviews:remove_author_from_review' %}">
          <li class="list-group-item" author-id="{{ review.author.id }}">
            <a href="/{{ review.author.username }}/">
              {{ review.author.profile.get_screen_name }}
            </a>
            <span class="badge">main author</span>
          </li>
          {% for author in review.co_authors.all %}
            <li  class="list-group-item" data-user-id="{{ author.id }}">
              <a href="{% url 'reviews' author.username %}">{{ author.profile.get_screen_name }}</a>
              {% if user.id == review.author.id %}
                <a href="javascript:void(0);" class="js-remove-author text-danger pull-right">
                  <span class="glyphicon glyphicon-remove"></span>
                </a>
              {% elif user.id == author.id %}
                <form method="post" action="{% url 'reviews:leave' %}" style="display: inline">
                  {% csrf_token %}
                  <input type="hidden" name="review-id" value="{{ review.id }}">
                  <a href="javascript:void(0);" class="js-leave text-danger pull-right">(leave)</a>
                </form>
              {% endif %}
            </li>
          {% endfor %}
        </ul>
        {% if user.id == review.author.id %}
          <div class="panel-footer">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add-author-modal">
              <span class="glyphicon glyphicon-plus"></span>
              Add author
            </button>
            <form method="post" action="{% url 'reviews:add_author_to_review' %}">
              {% csrf_token %}
              <input type="hidden" name="review-id" value="{{ review.pk }}">
              <div class="modal fade" id="add-author-modal">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <h4 class="modal-title">Add author</h4>
                    </div>
                    <div class="modal-body">
                      <div class="alert alert-info">
                        You may add someone that doesn't have a Parsifal Account. Just type his email adress and we will send an invitation. :)
                      </div>
                      <div class="form-group">
                        <label for="users" class="control-label">Contacts</label>
                        <select id="users" name="users" class="contacts" placeholder="Pick an author or invite someone..."></select>
                      </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                      <button type="submit" class="btn btn-success">Send invitation</button>
                    </div>
                  </div>
                </div>
              </div>
            </form>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
  
{% endblock content %}

enginetoday/advertise/templates/reviews/review_header.html
<h3 class="review-title">
  {% if user == review.author %}
    <a href="{% url 'settings' review.author.username review.name %}" class="btn btn-primary pull-right"><span class="glyphicon glyphicon-cog"></span> Review settings</a>
  {% endif %}
  <a href="{{ review.author.get_absolute_url }}" class="review-title-user">{{ review.author.profile.get_screen_name }}</a> 
  <span class="text-muted">/</span>
  <a href="{{ review.get_absolute_url }}">{{ review.title }}</a>
</h3>
<ul class="review-menu">
  <li{% if active_menu == "review"%} class="active"{% endif %}>
    <a href="{{ review.get_absolute_url }}">Review</a>
  </li>
  <li{% if active_menu == "planning"%} class="active"{% endif %}>
    <a href="{% url 'planning' review.author.username review.name %}">Planning</a>
  </li>
  <li{% if active_menu == "conducting"%} class="active"{% endif %}>
    <a href="{% url 'conducting' review.author.username review.name %}">Conducting</a>
  </li>
  <li{% if active_menu == "reporting"%} class="active"{% endif %}>
    <a href="{% url 'reporting' review.author.username review.name %}">Reporting</a>
  </li>
</ul>
<input type="hidden" id="review-id" value="{{ review.id }}">

enginetoday/advertise/templates/reviews/reviews.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}{{ page_user.profile.get_screen_name }} · engineToday{% endblock %}

{% block javascript %}
  <script type="text/javascript" src="{% static 'js/activities.js' %}?_=1"></script>
{% endblock javascript %}

{% block content %}
    <div class="media" style="margin-bottom: 20px;">
      <div class="media-left">
{#        <a href="{% url 'reviews' page_user.username %}">#}
          <img class="media-object img-circle" src="{{ page_user.profile.get_picture }}" alt="{{ page_user.profile.get_screen_name }}" style="width: 100px; height: 100px;">
        </a>
      </div>
      <div class="media-body media-middle">
        <div class="row">
          <div class="col-sm-12">
              <h2 class="media-heading">
                {{ page_user.get_full_name }}
                {% if user.is_authenticated %}
                  {% if user.id == page_user.id %}
                    <a href="{% url 'settings:settings' %}" class="btn btn-default btn-xs">
                      <span class="glyphicon glyphicon-pencil"></span>
                      Edit profile
                    </a>
                  {% else %}
                    {% if is_following %}
                      <span class="user-actions following update-count" data-user-id="{{ page_user.id }}">
                        <button class="btn btn-danger btn-xs" type="button"><span class="glyphicon glyphicon-remove"></span> Unfollow</button>
                      </span>
                    {% else %}
                      <span class="user-actions not-following update-count" data-user-id="{{ page_user.id }}">
                        <button class="btn btn-success btn-xs" type="button"><span class="glyphicon glyphicon-ok"></span> Follow</button>
                      </span>
                    {% endif %}
                  {% endif %}
                {% endif %}
              </h2>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12">
            <h5 style="margin-top: 5px;">
            {% if page_user.is_staff %}<span class="label label-primary" style="margin-right: 10px;">STAFF</span>{% endif %}
{#            <a href="{% url 'followers' page_user.username %}">#}
              Followers
              <span class="followers-count">{{ followers_count }}</span>
            </a>
            <span style="margin-left: 5px; margin-right: 5px; color: #aaa;">•</span>
{#            <a href="{% url 'following' page_user.username %}">#}
              Following
              <span class="following-count">{{ following_count }}</span>
            </a>
            </h5>
          </div>
        </div>
        <div class="row" style="color: #aaa;">
          <div class="col-sm-6">
            <span class="glyphicon glyphicon-user"></span> {{ page_user.username }} 
            {% if page_user.profile.public_email %}<span class="glyphicon glyphicon-envelope" style="margin-left: 10px;"></span> {{ page_user.profile.public_email }}{% endif %}
            {% if page_user.profile.url %}<span class="glyphicon glyphicon-globe" style="margin-left: 10px;"></span> <a href="{{ page_user.profile.get_url }}" target="_blank">{{ page_user.profile.get_url }}</a>{% endif %}
          </div>
          <div class="col-sm-6 text-right">
            {% if page_user.profile.institution %}<span class="glyphicon glyphicon-education"></span> {{ page_user.profile.institution }}{% endif %}
            {% if page_user.profile.location %}<span class="glyphicon glyphicon-map-marker" style="margin-left: 10px;"></span> {{ page_user.profile.location }}{% endif %}
            <span class="glyphicon glyphicon-time" style="margin-left: 10px;"></span> Joined on {{ page_user.date_joined|date:"d M Y" }}
          </div>
        </div>
      </div>
    </div>

    {% if user.id == page_user.id %}
      <div style="margin-bottom: 20px;">
{#        <a href="{% url 'reviews:new' %}" class="btn btn-primary">New review</a>#}
      </div>
      {% if user_reviews %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Work in progress</h3>
          </div>
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Title</th>
                <th>Authors</th>
                <th>Last update</th>
              </tr>
            </thead>
            <tbody>
              {% for review in user_reviews %}
                <tr>
                  <td><a href="/{{ review.author.username }}/{{ review.name }}/">{{ review.title }}</a></td>
                  <td>
{#                    <a href="{% url 'reviews' review.author.username %}">{{ review.author.profile.get_screen_name }}</a>{% for author in review.co_authors.all %}, <a href="/{{ author.username }}/">{{ author.profile.get_screen_name }}</a>{% endfor %}#}
                  </td>
                  <td>{{ review.last_update|date:"D d M Y" }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>  
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Published reviews</h3>
          </div>
          <div class="panel-body">You haven't published any systematic literature review yet.</div>
        </div>
      {% else %}
        <div class="well text-center" style="padding: 5em;">
          <span class="glyphicon glyphicon-book" style="font-size: 2.6em; color: #aaa;"></span>
          <h3 style="margin-top: 25px; margin-bottom: 25px;">You don't have any systematic literature review yet.</h3>
{#          <a href="{% url 'reviews:new' %}" class="btn btn-primary">Start a review</a>#}
        </div>
      {% endif %}
    {% else %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Published reviews</h3>
        </div>
        <div class="panel-body">{{ page_user.profile.get_screen_name }} haven't published any systematic literature review yet.</div>
      </div>
    {% endif %}

{% endblock content %}